### ISSUE TITLE
`react-native run-android error` Failed to install the app. Make sure you have the Android development environment set up

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/sample-app-mobile#39]
Getting the following error when trying to run `react-native run-android`
I do have Android studio set up and running and can start an emulator.

`error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Unable to install /Users/nikolayadvolodkin/Documents/source/Appium/sample-app-mobile/android/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE`

**Comment by wswebcreation** [comment]
Same answer as in https://github.com/saucelabs/sample-app-mobile/issues/40

Secondly, did you follow all the steps in the readme?
