### ISSUE TITLE
error React Native CLI uses autolinking for native dependencies

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/sample-app-mobile#40]
Environment is set up.
Ran command `react-native run-ios`
Got the following error
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-biometrics (to unlink run: "react-native unlink react-native-biometrics")
  - react-native-quick-actions (to unlink run: "react-native unlink react-native-quick-actions")
  - react-native-webview (to unlink run: "react-native unlink react-native-webview")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
```

**Comment by wswebcreation** [comment]
Hi @nadvolod 

Did it build or not? Normally these errors are not a problem.

Is there a specific reason why you want to build the app? This is normally done when you want to add new stuff in the app. For testing just use the apps in the release tab and change the path to the app in your config

**Comment by nadvolod** [comment]
@wswebcreation I wanted to have the app running for testing purposes and I was following the instructions. If those instructions are for Development/Contribution, we should update that because I was confused and thought that this is what's required to play with the app. If there are different instructions for demoing RDC then can you point me to those?
If this is the case, I can help move the Development/Contribution into a separate .md and link to it and also add a link to a section called How To Run App For Testing or something like that. Just let me know

**Comment by wswebcreation** [comment]
It's only for development, I'll update the docs asap
