### ISSUE TITLE
Mac OS Catalina Gatekeeper prevents Execution of iOS App on Simulator

### ISSUE THREAD

**Issue by dbrigginshaw** [saucelabs/sample-app-mobile#42]
Mac OS Catalina Gatekeeper is preventing the iOS Simulator release of the sample App from running on Simulators with the error “App is damaged and can't be opened. You should move it to the trash.”

This can be resolved with an override from a terminal window:

sudo xattr -rd com.apple.quarantine iOS.Simulator.SauceLabs.Mobile.Sample.app.2.1.1.app

**Comment by wswebcreation** [comment]
@dbrigginshaw 

Thanks for logging this, I've tried it on my local machine, also with Catalina, and I see the same, I'll make a new release today and upload it again.

**Comment by dbrigginshaw** [comment]
No problem Wim, just wanted to give you the heads up! It's up and running for me post issuing the xattr command.

**Comment by wswebcreation** [comment]
@dbrigginshaw 

I've build a new version and uploaded it, but when I try to install it Catalina is crying about all kinds of errors, strange, need to dive into this

**Comment by wswebcreation** [comment]
@dbrigginshaw 

Been checking this and it looks like it's only happening when you do manual installing and for example not with Appium/Appium Desktop. I'll add something in the docs for it. Thanks for flagging this

**Comment by wswebcreation** [comment]
@dbrigginshaw 

Added something in the docs, see https://github.com/saucelabs/sample-app-mobile#faq. Hope this is enough and clear. Thanks for flagging this. 

Closing this issue for now, but still open for discussion

**Comment by dbrigginshaw** [comment]
Thanks @wswebcreation that's great, clear on how to resolve :)
