### ISSUE TITLE
[Question] Is it possible get the network logs from an android emulator test?

### ISSUE THREAD

**Issue by NareshMurthy** [saucelabs/sample-app-mobile#70]
I have an automated test running on sauce android emulator - native app. There are few api calls emitted by the app based on the actions, Is there a way I can see the network logs going out from my android app while running the test on sauce labs?

Thanks!

**Comment by wswebcreation** [comment]
Hi @NareshMurthy 

Thanks for reaching out, but unfortunately we don't provide the logs. You might be able to capture the network traffic if you're using Sauce Connect together with Charles proxy and export it to a HAR-file
