### ISSUE TITLE
react-native run-ios is failing 

### ISSUE THREAD

**Issue by vishnu93tr** [saucelabs/sample-app-mobile#72]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening SwagLabsMobileApp.xcworkspace.

**Comment by wswebcreation** [comment]
Hi @vishnu93tr 

Strange, it should work. Can you explain the steps you did to build the app? Can you also provide more information about your local environment?

**Comment by vishnu93tr** [comment]
brew install node
brew install yarn
brew install watchman
yarn global add react-native-cli
sudo gem install cocoapods
cd ios
pod install->on ios folder
cd ..
yarn install
react-native run-ios

local env:mac os Mozowave
xcode version:11.3

**Comment by wswebcreation** [comment]
Can you also provide the following info of your machine
- yarn version
- node version
- npm version

Can you also provide more logs here to see which command during the build failed

Thanks

**Comment by vishnu93tr** [comment]
yarn version->1.22.10
node version->14.16.0

pod install output:
ET-C02T91MYG8WN:ios vishnu.vardhan$ pod install
Auto-linking React Native modules for target `SwagLabsMobileApp`: RNCAsyncStorage, RNCMaskedView, RNFS, RNGestureHandler, RNLocalize, RNPermissions, RNQuickAction, RNReanimated, RNScreens, RNVectorIcons, react-native-biometrics, react-native-camera, react-native-cameraroll, react-native-geolocation-service, react-native-safe-area-context, react-native-splash-screen, react-native-webview, and rn-fetch-blob
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
dyld: lazy symbol binding failed: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/vishnu.vardhan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/ffi-1.15.0/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

dyld: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/vishnu.vardhan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/ffi-1.15.0/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

Abort trap: 6

react-native run-ios logs:

info Found Xcode workspace "SwagLabsMobileApp.xcworkspace"
info Building (using "xcodebuild -workspace SwagLabsMobileApp.xcworkspace -configuration Debug -scheme SwagLabsMobileApp -destination id=3781844E-3F6A-488D-96CF-B27281AB3524")
(node:39879) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening SwagLabsMobileApp.xcworkspace. Run CLI with --verbose flag for more details.
note: Using new build system
note: Planning build
note: Using build description from disk
error: /Users/vishnu.vardhan/sample-app-mobile/ios/Pods/Target Support Files/Pods-SwagLabsMobileApp/Pods-SwagLabsMobileApp.debug.xcconfig: unable to open file (in target "SwagLabsMobileApp" in project "SwagLabsMobileApp") (in target 'SwagLabsMobileApp' from project 'SwagLabsMobileApp')
error: /Users/vishnu.vardhan/sample-app-mobile/ios/Pods/Target Support Files/Pods-SwagLabsMobileApp/Pods-SwagLabsMobileApp.debug.xcconfig: unable to open file (in target "SwagLabsMobileApp" in project "SwagLabsMobileApp") (in target 'SwagLabsMobileApp' from project 'SwagLabsMobileApp')
error: /Users/vishnu.vardhan/sample-app-mobile/ios/Pods/Target Support Files/Pods-SwagLabsMobileApp/Pods-SwagLabsMobileApp.debug.xcconfig: unable to open file (in target "SwagLabsMobileApp" in project "SwagLabsMobileApp") (in target 'SwagLabsMobileApp' from project 'SwagLabsMobileApp')
error: /Users/vishnu.vardhan/sample-app-mobile/ios/Pods/Target Support Files/Pods-SwagLabsMobileApp/Pods-SwagLabsMobileApp.debug.xcconfig: unable to open file (in target "SwagLabsMobileApp" in project "SwagLabsMobileApp") (in target 'SwagLabsMobileApp' from project 'SwagLabsMobileApp')


** BUILD FAILED **

**Comment by wswebcreation** [comment]
Can you remove the pod_lock file and try the installation again?

**Comment by wswebcreation** [comment]
Closing it now due to inactivity
