### ISSUE TITLE
Error: Cannot start the 'com.swaglabsmobileapp' application.

### ISSUE THREAD

**Issue by BartVanRaemdonck** [saucelabs/sample-app-mobile#79]
When you try to inspect the apk app with Appium you get this error.

![Schermafbeelding 2021-04-30 om 19 29 12](https://user-images.githubusercontent.com/11335721/116732126-f56dfe80-a9ea-11eb-857f-95b551e6ca51.png)

**Comment by wswebcreation** [comment]
Hi @BartVanRaemdonck 

You need to wait for the activity as used here https://github.com/saucelabs/sample-app-mobile/blob/main/tests/e2e/config/wdio.android.local.emu.conf.js#L19

Closing this because it's not an issue with Appium or the app
