### ISSUE TITLE
Not able to open app

### ISSUE THREAD

**Issue by PulivendarReddy** [saucelabs/sample-app-mobile#94]
unable to open file

![image](https://user-images.githubusercontent.com/109149765/178978777-edfa4678-06d2-4119-a28d-4111878a3844.png)

**Comment by wswebcreation** [comment]
Hi @PulivendarReddy 

Thanks for this issue, if you would add `'appium:appWaitActivity': 'com.swaglabsmobileapp.MainActivity',` it should work.

Can you try that?
